Add disk create to VM resource
skytap/terraform-provider-skytap pull request #10
Opened 2018-12-17 17:03 UTC by ja6a

Add new disk element to the VM resource. 
The allows the ability to add disks to the VM.
It is a Force New at this stage.
Refactor to make separation between create and update flows cleaner.

Note: rebased on feature/cpu because it is not possible to merge to master at this time.

2019-01-02 09:17 UTC, pegerto commented
Requires rebase

2019-01-02 09:21 UTC, pegerto requested changes
Rebase necesary

2019-01-02 12:02 UTC, pegerto requested changes
Missing an acceptance test.

2019-01-02 12:02 UTC, pegerto commented on skytap/resource_skytap_vm.go
> +	forceRunning := true
We should not change the behaviour of the code during testing.

2019-01-02 12:02 UTC, pegerto commented on skytap/resource_skytap_vm.go
> +	if err != nil {
d.Set of vm.Name been vm.Name a single value should be safe.

2019-01-02 12:02 UTC, pegerto commented on skytap/resource_skytap_vm.go
> +	err = d.Set("environment_id", environmentID)
d.Set of int should be safe.

2019-01-02 12:05 UTC, pegerto commented on skytap/resource_skytap_vm.go
> +		opts.Hardware.NewDisks.Sizes = make([]int, d.Get("disk.#").(int))
Is there a max number of disk that we can create?

2019-01-02 12:25 UTC, ja6a commented on skytap/resource_skytap_vm.go
> +		opts.Hardware.NewDisks.Sizes = make([]int, d.Get("disk.#").(int))
This is not specified in the docs AFAIK.

2019-01-02 12:27 UTC, ja6a commented on skytap/resource_skytap_vm.go
> +	err = d.Set("environment_id", environmentID)
I propose to remove the nil checks in a future PR. I will update this comment when this is done.

2019-01-02 12:28 UTC, ja6a commented on skytap/resource_skytap_vm.go
> +	forceRunning := true
I propose to remove this in a future PR. I will update this comment when this is done.

2019-01-02 12:28 UTC, ja6a commented on skytap/resource_skytap_vm.go
> +	if err != nil {
I propose to remove the nil checks in a future PR. I will update this comment when this is done.

2019-01-02 12:30 UTC, ja6a commented
The acceptance test is added in the next PR.

2019-01-02 12:43 UTC, pegerto approved these changes

2019-01-02 12:44 UTC, merged

2019-01-03 16:21 UTC, ja6a commented on skytap/resource_skytap_vm.go
> +	forceRunning := true
Removed

2019-01-03 16:21 UTC, ja6a commented on skytap/resource_skytap_vm.go
> +	err = d.Set("environment_id", environmentID)
error checks removed.

2019-01-03 16:21 UTC, ja6a commented on skytap/resource_skytap_vm.go
> +	if err != nil {
error checks removed.