Add attributes providing access to maps of computed VM resource settings
skytap/terraform-provider-skytap pull request #5
Opened 2018-12-13 17:27 UTC by ja6a

Each network interface is contained within a set. Within each set is a set of published services. Both sets will contain computed values. Access to these values is required within the terraform state files.
The values are:
External IP address
External port for the published services.

The documentation contains instructions on how to use the new attributes.

2018-12-13 17:29 UTC, night0wl commented
👍

2018-12-13 19:57 UTC, pegerto commented on skytap/resource_skytap_vm.go
> +			"external_ips": {
Double check if we  can have only a string, as all the  ips will be the same given a VM

2018-12-13 19:57 UTC, pegerto commented on skytap/resource_skytap_vm.go
> +		var ipMaps = []map[string]interface{}{make(map[string]interface{}), make(map[string]interface{})}
Use of a better name publishServices,

2018-12-13 19:57 UTC, pegerto commented on skytap/resource_skytap_vm.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
I think that may be a TypeInt

2018-12-13 19:57 UTC, pegerto commented on skytap/structures_test.go
> +const exampleInterfaceAndPortsListResponse = `[
this is testdata

2018-12-13 19:58 UTC, pegerto approved these changes

2018-12-13 19:59 UTC, pegerto requested changes
Looks good from the accessibility perspective, require changes,.

2018-12-14 10:32 UTC, ja6a commented on skytap/resource_skytap_vm.go
> +		var ipMaps = []map[string]interface{}{make(map[string]interface{}), make(map[string]interface{})}
done

2018-12-14 10:32 UTC, ja6a commented on skytap/resource_skytap_vm.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
reverted back to int

2018-12-14 10:41 UTC, ja6a commented on skytap/structures_test.go
> +const exampleInterfaceAndPortsListResponse = `[
done

2018-12-14 16:23 UTC, pegerto commented
This will need to be replaced with name services, allow the exported service to have a mandatory name.
- Update the documentation.
- Update the changelog accordingly.

2018-12-14 16:24 UTC, pegerto requested changes
As  discussed update with named services.

2018-12-14 16:47 UTC, ja6a commented
See issue #5 for a description of the revised definition using named services.

2018-12-21 08:46 UTC, ja6a commented
We are going to implement this in a different way. See issue #7

2018-12-21 08:46 UTC, closed without merging